language: go

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -bench . -benchtime 50ms -coverprofile=is.coverprofile
  - goveralls -coverprofile=is.coverprofile -service=travis-ci

go:
  - 1.2
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip